<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <Company>Nexus</Company>
    <Product>Project Nexus</Product>
    <Copyright>Copyright © Nexus</Copyright>
  </PropertyGroup>
</Project>
