<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Nexus.Catalog.Application</RootNamespace>
    <AssemblyName>Nexus.Catalog.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Catalog.Domain\Nexus.Catalog.Domain.csproj" />
    <ProjectReference Include="..\Nexus.Catalog.Contracts\Nexus.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\src\Nexus.Abstractions\Nexus.Abstractions.csproj" />
  </ItemGroup>
</Project>
