@Nexus.UserService_HostAddress = http://localhost:8081

GET {{Nexus.UserService_HostAddress}}/api/v1/health
Accept: application/json

###

GET {{Nexus.UserService_HostAddress}}/health
Accept: application/json

###

GET {{Nexus.UserService_HostAddress}}/openapi/v1.json
Accept: application/json
