<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Nexus.Commerce.Application</RootNamespace>
    <AssemblyName>Nexus.Commerce.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Commerce.Domain\Nexus.Commerce.Domain.csproj" />
    <ProjectReference Include="..\Nexus.Commerce.Contracts\Nexus.Commerce.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\src\Nexus.Abstractions\Nexus.Abstractions.csproj" />
  </ItemGroup>
</Project>
