<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Nexus.Auction.Application</RootNamespace>
    <AssemblyName>Nexus.Auction.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Auction.Domain\Nexus.Auction.Domain.csproj" />
    <ProjectReference Include="..\Nexus.Auction.Contracts\Nexus.Auction.Contracts.csproj" />
    <ProjectReference Include="..\..\..\..\src\Nexus.Abstractions\Nexus.Abstractions.csproj" />
  </ItemGroup>
</Project>
