<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Nexus.Notification.Api</RootNamespace>
    <AssemblyName>Nexus.Notification.Api</AssemblyName>
    <LaunchBrowser>true</LaunchBrowser>
    <LaunchUrl>swagger</LaunchUrl>
    <ApplicationUrl>http://localhost:8086</ApplicationUrl>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Notification.Application\Nexus.Notification.Application.csproj" />
    <ProjectReference Include="..\Nexus.Notification.Infrastructure\Nexus.Notification.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\src\Nexus.AspNetCore\Nexus.AspNetCore.csproj" />
  </ItemGroup>
</Project>
