<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Nexus.Fulfillment.Domain</RootNamespace>
    <AssemblyName>Nexus.Fulfillment.Domain</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Nexus.Abstractions\Nexus.Abstractions.csproj" />
  </ItemGroup>
</Project>
