<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Nexus.Auction.Infrastructure</RootNamespace>
    <AssemblyName>Nexus.Auction.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Auction.Domain\Nexus.Auction.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\src\Nexus.Persistence\Nexus.Persistence.csproj" />
  </ItemGroup>
</Project>
