<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Nexus.Fulfillment.Api</RootNamespace>
    <AssemblyName>Nexus.Fulfillment.Api</AssemblyName>
    <LaunchBrowser>true</LaunchBrowser>
    <LaunchUrl>swagger</LaunchUrl>
    <ApplicationUrl>http://localhost:8085</ApplicationUrl>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nexus.Fulfillment.Application\Nexus.Fulfillment.Application.csproj" />
    <ProjectReference Include="..\Nexus.Fulfillment.Infrastructure\Nexus.Fulfillment.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\src\Nexus.AspNetCore\Nexus.AspNetCore.csproj" />
  </ItemGroup>
</Project>
